version: '3.7'

services:
    mongo:
        container_name: DB-SERVER
        restart: always
        image: mongo
        ports: 
            - 27017:27017
    backend:
        container_name: BACKEND-SERVER
        restart: always
        build: ./backend/
        command: npm start
        volumes:
            - ./backend/:/usr/app
            - /usr/app/node_modules
        ports:
            - 8282:8282
        depends_on: 
            - mongo
    frontend:
        container_name: FRONTEND-SERVER
        restart: always
        build: ./frontend/
        command: npm start
        volumes:
            - ./frontend/:/usr/app
            - /usr/app/node_modules
        ports:
            - 3000:3000
        depends_on: 
            - backend