version: '3.7'

services:
    mongo:
        container_name: DB-SERVER
        restart: always
        image: mongo
        ports: 
            - 27017:27017
    node:
        container_name: BACKEND-SERVER
        restart: always
        build: ./backend
        command: npm start
        ports:
            - 8282:8282
        volumes:
            - ./backend:/usr/src/app
        depends_on: 
            - mongo